import Phaser from 'phaser';
import './styles.css';
import {recipes,step} from './data/recipes';
import {chapters,type CountryId,type CatalogDish} from './data/catalog';
import {SaveStore} from './core/save';
import {AudioManager} from './core/audio';
import {scoreStep,average,stars} from './core/scoring';
import {KitchenScene} from './scenes/KitchenScene';
import {node,button,confirmDialog} from './ui/dom';
import type {Recipe,ActiveRun,StepResult,Difficulty,RunMode} from './types';
const APP_VERSION='0.7.0';
const store=new SaveStore({...Object.fromEntries(recipes.map(r=>[r.id,r.steps.length])),'service-dumplings':7}),audio=new AudioManager(store.data.settings);
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<header><div class="brand"><span class="brand-mark" aria-hidden="true">WK</span><div><small>WORLD KITCHEN · STUDIO EDITION</small><h1>Học viện bếp thế giới</h1></div></div><nav id="nav" aria-label="Điều hướng chính"></nav></header><div id="rotate">↻ Giao diện đã tối ưu dọc/ngang · xoay máy bất cứ lúc nào</div><main id="page" class="page"></main><section id="play"><div id="order-strip" hidden></div><div id="hud"><div class="hud-copy"><small id="step-label"></small><h2 id="step-title"></h2><p id="instruction"></p><div id="step-dots" aria-label="Tiến trình công thức"></div></div><div class="hud-tools"><div class="quality-card"><span>CHUẨN THAO TÁC</span><b id="live-quality">0 / 0</b></div><div class="timer-card"><span>CÒN LẠI</span><b id="timer">-- giây</b></div><div id="pause-slot"></div></div></div><div id="game-wrap"><div class="stage-label" id="stage-label">BÀN SƠ CHẾ</div><div id="game"></div><div id="touch-feedback" aria-hidden="true"></div><div id="overlay"><div class="dialog" id="dialog"></div></div></div><div id="foot"><div class="progress-copy"><span>TIẾN ĐỘ CÔNG ĐOẠN</span><progress id="progress" max="1"></progress></div><span id="feedback" role="status">Sẵn sàng vào bếp</span></div><div id="heat-controls"></div></section><aside id="update-toast" hidden role="status"><div><strong>Có phiên bản bếp mới</strong><span>Tiến trình hiện tại vẫn được giữ trên thiết bị.</span></div><button id="apply-update">Cập nhật ngay</button><button id="dismiss-update" class="secondary" aria-label="Để sau">Để sau</button></aside>`;
const get=(id:string)=>document.getElementById(id)!;
const page=get('page'),play=get('play'),scene=new KitchenScene();
let game:Phaser.Game|null=null,run:ActiveRun|null=null,recipe:Recipe|null=null,practice=false,runMode:RunMode='lesson',phase:'menu'|'tutorial'|'running'|'paused'|'review'='menu',stepResult:StepResult|null=null;
let selectedCountry:CountryId='china';
interface InstallPromptEvent extends Event {prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>}
let installPrompt:InstallPromptEvent|null=null;
let swRegistration:ServiceWorkerRegistration|null=null;
let servicePrepared=false;
const serviceStock={produce:0,protein:0,serviceware:0};
interface ServiceOrder {avatar:string;name:string;quote:string;dish:Recipe;tags:string[];accent:string;patience:number;reward:number}
let activeOrder:ServiceOrder|null=null;
const creativeRecipe:Recipe={id:'creative',name:'Hộp nguyên liệu bí mật',country:'Bếp sáng tạo',emoji:'✦',description:'Một ca ngẫu hứng đi qua bảy công việc bếp hoàn toàn khác nhau.',steps:[
 {...step('wash','rau theo mùa'),name:'Rửa rau vừa hái'},
 {...step('grate','củ sen'),target:8,name:'Bào củ sen thành sợi'},
 {...step('knead','bột gia vị'),target:6,name:'Nhào khối bột thơm'},
 {...step('assemble','topping theo mùa'),target:6,name:'Tự lắp ráp món'},
 {...step('season','sốt bí mật'),target:5,name:'Nêm sốt theo nhịp'},
 {...step('fry','nguyên liệu bí mật'),name:'Canh lửa áp chảo'},
 {...step('plate','món sáng tạo'),name:'Tự tay hoàn thiện đĩa'}
]};
const serviceDumplingRecipe:Recipe={id:'service-dumplings',name:'Bánh xếp giòn · suất lớn',country:'Quầy món nóng',emoji:'🥟',art:'/assets/dishes/potstickers-v1.png',description:'Đọc đúng khẩu phần, làm nhân, gấp bánh, canh đáy giòn và giao sốt riêng trước khi khách hết kiên nhẫn.',steps:[
 {...step('choose','suất L'),name:'Chia đúng suất lớn',hint:'Phiếu order ghi suất L — chạm đúng đĩa phần lớn'},
 {...step('mince','bắp cải và hành lá'),target:12,name:'Băm rau làm nhân'},
 {...step('mix','nhân thịt'),name:'Trộn nhân đúng độ kết dính'},
 {...step('fold'),name:'Gấp kín từng chiếc bánh'},
 {...step('fry','bánh xếp'),name:'Canh đáy bánh vàng giòn'},
 {...step('pour','nước'),name:'Châm nước hấp mềm mặt bánh'},
 {...step('plate','bánh xếp và sốt riêng'),name:'Xếp suất lớn và tách sốt riêng'}
]};
const serviceOrders:ServiceOrder[]=[
 {avatar:'LA',name:'Chị Lan',quote:'“Cho chị suất lớn bánh xếp, đáy thật giòn và phần sốt để riêng. Chị đang vội!”',dish:serviceDumplingRecipe,tags:['SUẤT L','GIÒN ĐÁY','SỐT RIÊNG'],accent:'coral',patience:65,reward:58},
 {avatar:'AN',name:'An',quote:'“Cho em gà Cung Bảo ít cay, miếng gà nhỏ đều và đậu phộng rang kỹ nhé!”',dish:recipes[1],tags:['ÍT CAY','MIẾNG ĐỀU','ĐẬU PHỘNG RANG'],accent:'green',patience:75,reward:64},
 {avatar:'BK',name:'Bếp trưởng Khang',quote:'“Một cơm chiên rau củ: hạt cơm tơi, rau còn giòn và tuyệt đối không đọng dầu.”',dish:recipes[2],tags:['CƠM TƠI','RAU GIÒN','ÍT DẦU'],accent:'violet',patience:85,reward:68}
];
function unlock(r:Recipe){return !r.requires||(store.data.best[r.requires]??0)>=70}
function stationLabel(kind:Recipe['steps'][number]['kind']){return({find:'KHO NGUYÊN LIỆU',choose:'QUẦY CHIA KHẨU PHẦN',wash:'BỒN RỬA SƠ CHẾ',slice:'BÀN KỸ THUẬT DAO',dice:'BÀN KỸ THUẬT DAO',mince:'BÀN KỸ THUẬT DAO',mix:'TRẠM PHỐI TRỘN',fold:'BÀN BỘT & TẠO HÌNH',boil:'TRẠM BẾP NHIỆT',pour:'TRẠM ĐỊNH LƯỢNG',fry:'TRẠM ÁP CHẢO',season:'TRẠM NÊM NẾM',plate:'QUẦY HOÀN THIỆN',grate:'TRẠM BÀO & XỬ LÝ',knead:'BÀN NHÀO BỘT',assemble:'BÀN LẮP RÁP TỰ DO'} as const)[kind]}
function showPage(active:'menu'|'practice'|'settings'|'service'='menu'){scene.paused=true;scene.cancel();play.style.display='none';page.style.display='block';page.replaceChildren();phase='menu';const items:[string,()=>void,'menu'|'practice'|'settings'][]=[['Món ăn',menu,'menu'],['Luyện tập',practiceMenu,'practice'],['Cài đặt',settings,'settings']];const buttons=items.map(([label,fn,id])=>{const b=button(label,fn,true);if(id===active){b.classList.add('active');b.setAttribute('aria-current','page')}return b});get('nav').replaceChildren(...buttons)}
function status(text=store.message){page.append(node('p',text,'status'))}
function showCatalogDish(dish:CatalogDish){const d=node('dialog');d.className='recipe-dialog';d.append(node('div','WK','recipe-dialog-icon'),node('div',dish.name.toUpperCase(),'eyebrow'),node('h2',dish.viName||dish.name),node('h3','Nguyên liệu'),node('p',dish.ingredients));const title=node('h3','Quy trình'),list=node('ol');dish.actions.forEach(action=>list.append(node('li',action)));d.append(title,list);if(dish.sourceIncomplete)d.append(node('p','Ghi chú: nội dung Tempura trong tệp nguồn bị cắt ở bước cuối; quy trình này đang để trạng thái cần duyệt.','source-warning'));const actions=node('div','','actions');actions.append(button('Đóng',()=>d.close()));d.append(actions);d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal()}
function menu(){showPage('menu');const hero=node('section','','hero academy-hero'),intro=node('div','','hero-copy');intro.append(node('div','WORLD CULINARY WORKSHOP','eyebrow'),node('h2','Vào học viện.\nNấu bằng đôi tay.'),node('p','Mỗi công thức là một ca thực hành trực tiếp: chọn đúng nguyên liệu, làm chủ đường dao, nhiệt độ và thời điểm hoàn thiện món.'));const heroActions=node('div','','actions');heroActions.append(button(store.data.active?'Tiếp tục bài đang học':'Vào bài học đầu tiên',store.data.active?resume:()=>start(recipes[0])),button('Phòng luyện kỹ năng',practiceMenu,true));intro.append(heroActions);const heroArt=node('div','','hero-kitchen');const heroPhoto=node('img');heroPhoto.src='/assets/dishes/potstickers-v1.png';heroPhoto.alt='Bánh xếp áp chảo vừa hoàn thiện';heroArt.append(heroPhoto,node('span','BÀI HỌC ĐỀ XUẤT','hero-photo-label'));const heroDetails=node('div','','hero-details');for(const [value,label] of [['09','CÔNG ĐOẠN'],['16','CÔNG VIỆC'],['100','ĐIỂM TỐI ĐA']]){const item=node('div');item.append(node('strong',value),node('small',label));heroDetails.append(item)}heroArt.append(heroDetails);hero.append(intro,heroArt);page.append(hero);
 const bestScores=Object.values(store.data.best);const averageBest=bestScores.length?bestScores.reduce((a,b)=>a+b,0)/bestScores.length:0;const stats=node('section','','stats');for(const [value,label] of [[String(store.data.completed),'LƯỢT HOÀN THÀNH'],[`${recipes.filter(unlock).length}/${recipes.length}`,'MÓN ĐÃ MỞ'],[bestScores.length?averageBest.toFixed(0):'—','ĐIỂM TRUNG BÌNH']]){const item=node('div','','stat');item.append(node('strong',value),node('span',label));stats.append(item)}page.append(stats);
 const modeHead=node('div','','section-head');const modeCopy=node('div');modeCopy.append(node('div','MỖI CA · MỘT NHỊP CHƠI','eyebrow'),node('h2','Hôm nay bạn muốn vào bếp kiểu nào?'));modeHead.append(modeCopy,node('span','16 công việc · 7 không gian bếp','unlock-note'));page.append(modeHead);const modes=node('section','','mode-grid');
 const modeCards=[
  {badge:'CÂU CHUYỆN',title:'Học công thức',copy:'Đi theo giáo trình, mở món mới và lưu điểm cao.',detail:'Nhịp thư thả · có hướng dẫn',action:'Tiếp tục học',run:()=>start(recipes.find(r=>!store.data.best[r.id]&&unlock(r))??recipes[0])},
  {badge:'RUSH ORDER',title:'Ca phục vụ theo yêu cầu',copy:'Đọc lời khách, chọn order phù hợp rồi xử lý theo ưu tiên riêng.',detail:'Yêu cầu biến đổi · nhịp liền mạch',action:'Mở quầy phục vụ',run:serviceShift},
  {badge:'CHEF\'S TABLE',title:'Hộp nguyên liệu bí mật',copy:'Bảy công việc khác nhau nối liền trong một ca ngẫu hứng.',detail:'Không modal giữa trạm · tự do thử',action:'Mở hộp bí mật',run:()=>start(creativeRecipe,true,'creative')}
 ];
 modeCards.forEach((m,i)=>{const card=node('article','','mode-card mode-'+i);card.append(node('span',m.badge,'eyebrow'),node('h3',m.title),node('p',m.copy),node('small',m.detail),button(m.action,m.run));modes.append(card)});page.append(modes);
 if(store.data.active){const banner=node('div','','banner');banner.append(node('span',`Bạn đang nấu ${recipes.find(r=>r.id===store.data.active?.recipeId)?.name}. Tiếp tục từ bước ${store.data.active.index+1}?`),button('Tiếp tục món',resume),button('Bỏ lượt lưu',()=>confirmDialog('Xóa lượt đang nấu? Điểm cao nhất vẫn được giữ.',()=>{store.checkpoint(null);menu()}),true));page.append(banner)}
 const passportHead=node('div','','section-head');const passportCopy=node('div');passportCopy.append(node('div','BẢN ĐỒ HỌC VIỆN','eyebrow'),node('h2','Các nhà hàng đào tạo'));passportHead.append(passportCopy,node('span','Hoàn thành kỳ thi để đi tiếp','unlock-note'));page.append(passportHead);const countryGrid=node('div','','country-grid academy-map');const countryIcons:Record<CountryId,string>={china:'中',italy:'IT',mexico:'MX',japan:'日'};for(const [chapterIndex,chapter] of chapters.entries()){const available=chapter.id==='china';const card=button('',()=>{if(available){selectedCountry=chapter.id;menu()}},true);card.className='country-card academy-stop'+(chapter.id===selectedCountry?' active':'');card.disabled=!available;card.setAttribute('aria-label',available?`Vào nhà hàng ${chapter.name}`:`Nhà hàng ${chapter.name} đang khóa`);card.append(node('span',available?'NHÀ HÀNG ĐANG HỌC':`NHÀ HÀNG ${String(chapterIndex+1).padStart(2,'0')}`),node('b',countryIcons[chapter.id],'restaurant-seal'),node('strong',chapter.name),node('small',available?`${chapter.dishes.length} công thức trong giáo trình`:'🔒 Vượt kỳ thi trước để mở'));countryGrid.append(card)}page.append(countryGrid);
 const current=chapters.find(chapter=>chapter.id===selectedCountry)!;const sectionHead=node('div','','section-head');const headCopy=node('div');headCopy.append(node('div',`NHÀ HÀNG ${chapters.indexOf(current)+1} · ${current.subtitle.toUpperCase()}`,'eyebrow'),node('h2',`Giáo trình ${current.name}`));sectionHead.append(headCopy,node('span',selectedCountry==='china'?'Đạt 70 điểm để qua từng bài':'Chưa mở khóa','unlock-note'));page.append(sectionHead);
 if(selectedCountry==='china'){const grid=node('div','','grid recipe-grid');for(const [index,r] of recipes.entries()){const card=node('article','','card recipe-card'),best=store.data.best[r.id],available=unlock(r);card.classList.toggle('locked',!available);const visual=node('div','','card-visual'),food=r.art?node('img'):node('div',r.emoji);food.className=r.art?'food-photo':'food';if(r.art&&(food instanceof HTMLImageElement)){food.src=r.art;food.alt=`Thành phẩm ${r.name}`;food.loading='lazy'}visual.append(node('span',String(index+1).padStart(2,'0'),'card-number'),food);if(!available)visual.append(node('span','KHÓA','lock'));card.append(visual,node('div',r.country.toUpperCase(),'eyebrow'),node('h3',r.name),node('p',r.description));const meta=node('div','','card-meta');meta.append(node('span',`${r.steps.length} thao tác`),node('span',best===undefined?'Chưa nấu':`${best.toFixed(1)} điểm`));card.append(meta,node('div',best===undefined?'☆☆☆☆☆':'★'.repeat(stars(best))+'☆'.repeat(5-stars(best)),'stars'));const b=button(available?'Vào bếp →':'Đạt 70 điểm món trước',()=>start(r));b.disabled=!available;card.append(b);grid.append(card)}page.append(grid)}
 const planned=current.dishes.filter(dish=>!dish.playableId||selectedCountry!=='china');if(planned.length){const plannedHead=node('div','','planned-head');plannedHead.append(node('h3',selectedCountry==='china'?'Các bài học sắp hoàn thiện':'Giáo trình nhà hàng'),node('p','Mỗi công thức sẽ trở thành một chuỗi mini-game thao tác, không phải thẻ sưu tầm món ăn.'));page.append(plannedHead);const catalogGrid=node('div','','catalog-grid lesson-list');planned.forEach((dish,index)=>{const card=node('article','','catalog-card lesson-card');card.append(node('span',String(recipes.length+index+1).padStart(2,'0'),'lesson-number'));const copy=node('div');copy.append(node('small',dish.name),node('h3',dish.viName||dish.name),node('p',`${dish.actions.length} bài thực hành · ${dish.ingredients.split(',').length} nhóm nguyên liệu`));card.append(copy,button('Xem giáo trình',()=>showCatalogDish(dish),true));catalogGrid.append(card)});page.append(catalogGrid)}const exam=node('section','','exam-card');exam.append(node('span','★','exam-trophy'));const examCopy=node('div');examCopy.append(node('small','KỲ THI NHÀ HÀNG','eyebrow'),node('h3',`Chứng chỉ Ẩm thực ${current.name}`),node('p','Hoàn thành các công thức và đạt điểm yêu cầu để bước vào bài thi tổng hợp.'));exam.append(examCopy,button('Chưa đủ điều kiện',()=>{},true));(exam.lastElementChild as HTMLButtonElement).disabled=true;page.append(exam);status(`Đã hoàn thành ${store.data.completed} lượt nấu. ${store.message}`)}
function serviceShift(){
 showPage('service');const top=node('section','','service-hero');const copy=node('div');copy.append(node('div',servicePrepared?'ĐANG MỞ CỬA · 11:45':'CHUẨN BỊ CA · 11:30','eyebrow'),node('h2',servicePrepared?'Khách đã tới. Đọc order rồi mới nấu.':'Chuẩn bị bếp trước giờ mở cửa.'),node('p',servicePrepared?'Mỗi khách có món, khẩu phần, thời gian chờ và tiêu chí riêng. Sai phần ăn, quá lửa hoặc giao trễ sẽ mất tip.':'Nhập đủ rau củ, thịt/cơm và dụng cụ phục vụ. Chi phí chuẩn bị ảnh hưởng số tiền còn lại của ca bán hàng.'));const queue=node('div','','queue-badge');queue.append(node('strong',servicePrepared?'03':'400k'),node('span',servicePrepared?'KHÁCH ĐANG CHỜ':'TIỀN MẶT ĐẦU CA'));top.append(copy,queue);page.append(top);
 if(!servicePrepared){const stockHead=node('div','','shop-section-head');stockHead.append(node('div','KHO ĐẦU CA','eyebrow'),node('h3','Nhập tối thiểu 5 phần mỗi nhóm'));page.append(stockHead);const stockGrid=node('section','','stock-grid');const items=[{key:'produce' as const,icon:'RAU',name:'Rau củ & gia vị',cost:'4,5k / phần'},{key:'protein' as const,icon:'ĐẠM',name:'Thịt, gạo & bột',cost:'8k / phần'},{key:'serviceware' as const,icon:'ĐĨA',name:'Đĩa, hộp & giấy gói',cost:'2k / phần'}];items.forEach(item=>{const card=node('article','','stock-card');const amount=node('strong',String(serviceStock[item.key]),'stock-amount');const minus=button('−',()=>{serviceStock[item.key]=Math.max(0,serviceStock[item.key]-5);serviceShift()},true);minus.setAttribute('aria-label',`Bớt ${item.name}`);const plus=button('+5',()=>{serviceStock[item.key]+=5;serviceShift()});plus.setAttribute('aria-label',`Thêm ${item.name}`);const stepper=node('div','','stock-stepper');stepper.append(minus,amount,plus);card.append(node('span',item.icon,'stock-icon'),node('h3',item.name),node('p',item.cost),stepper);stockGrid.append(card)});page.append(stockGrid);const ready=Object.values(serviceStock).every(n=>n>=5),prepBar=node('section','','prep-bar');const prepCopy=node('div');prepCopy.append(node('strong',ready?'Bếp đã sẵn sàng':'Còn thiếu nguyên liệu'),node('span',ready?'Mở cửa để khách đầu tiên vào quầy.':'Mỗi nhóm cần ít nhất 5 phần.'));const open=button('Mở cửa đón khách →',()=>{servicePrepared=true;serviceShift()});open.disabled=!ready;prepBar.append(prepCopy,open);page.append(prepBar);status('Kho và ca bán hàng đang được giữ trên thiết bị trong phiên chơi này.');return}
 const orders=serviceOrders;
 const queueNav=node('nav','','customer-queue');queueNav.setAttribute('aria-label','Khách đang chờ');orders.forEach((order,index)=>{const item=node('div','','queue-person');item.append(node('span',order.avatar),node('strong',order.name),node('small',index===0?'Đang gọi món':`Chờ số ${index+1}`));queueNav.append(item)});page.append(queueNav);
 const grid=node('section','','customer-grid');orders.forEach((order,index)=>{const card=node('article','','customer-order '+order.accent);const head=node('div','','customer-head');head.append(node('span',order.avatar,'customer-avatar'),node('div',`ORDER #${String(index+1).padStart(2,'0')} · ${order.name.toUpperCase()}`,'eyebrow'));card.append(head,node('blockquote',order.quote),node('h3',order.dish.name));const meta=node('div','','order-meta');meta.append(node('span',`⏱ ${order.patience}s`),node('span',`+${order.reward}k`));const tags=node('div','','order-tags');order.tags.forEach(tag=>tags.append(node('span',tag)));const take=button('Nhận order và vào quầy',()=>{activeOrder=order;void start(order.dish,false,'rush')});card.append(meta,tags,take);grid.append(card)});page.append(grid);
 const note=node('section','','design-note');note.append(node('strong','Vòng lặp ca bán hàng mới'),node('p','Chuẩn bị kho → mở cửa → đọc order → thao tác đúng món → giao khách → nhận tiền và tip. Đây là luồng chính; phòng luyện kỹ năng chỉ còn là nơi tập riêng từng thao tác.'));page.append(note);status('Tiến trình món và cài đặt được tự lưu cục bộ trên thiết bị này.');
}
function practiceMenu(){showPage('practice');const top=node('div','','page-title');top.append(node('div','PHÒNG THỰC HÀNH','eyebrow'),node('h2','Bài tập có mục tiêu'),node('p','Mỗi bài có chỉ tiêu rõ ràng về độ mỏng, độ đều, nhịp và thời gian. Hoàn thành mục tiêu rồi mới chuyển sang kỹ năng khó hơn.'));page.append(top);const goals=[
 {icon:'TH',level:'CƠ BẢN',title:'12 lát thật mỏng',goal:'Thái đủ 12 lát tỏi và ớt trong 45 giây',standard:'Mục tiêu: ≥ 80 điểm',s:{...step('slice','tỏi và ớt'),target:12,par:25,limit:45,name:'Thái 12 lát thật mỏng',hint:'Giữ đường dao thẳng và đều; khoảng cách lát cắt quyết định độ mỏng'}},
 {icon:'HL',level:'CHÍNH XÁC',title:'Hạt lựu nhỏ và đều',goal:'Hoàn thành 14 đường cắt cà rốt',standard:'Mục tiêu: ≥ 85% chính xác',s:{...step('dice','cà rốt'),target:14,par:32,limit:60,name:'Cắt hạt lựu mịn'}},
 {icon:'BM',level:'NHỊP ĐỘ',title:'Băm phủ đều mặt thớt',goal:'Theo đúng 18 nhịp dao, không bỏ vùng',standard:'Mục tiêu: không quá 2 lỗi',s:{...step('mince','bắp cải và hành lá'),target:18,par:22,limit:45,name:'Băm rau phủ đều'}},
 {icon:'TR',level:'KIỂM SOÁT',title:'Ba vòng trộn chuẩn',goal:'Trộn một chiều, không đi qua tâm tô',standard:'Mục tiêu: ≥ 90% chính xác',s:{...step('mix','nhân thịt'),target:3,par:20,limit:50,name:'Trộn nhân đúng kỹ thuật'}},
 {icon:'GP',level:'TỈ MỈ',title:'Ba nếp gấp kín',goal:'Gấp đúng điểm đầu và vùng đích',standard:'Mục tiêu: 3/3 nếp đẹp',s:{...step('fold'),par:22,limit:50,name:'Gấp bánh kín mép'}},
 {icon:'AP',level:'PHẢN XẠ',title:'Canh bốn mặt chảo',goal:'Lấy đủ bốn miếng trong vùng chín đẹp',standard:'Mục tiêu: không cháy miếng nào',s:{...step('fry','bánh xếp'),par:18,limit:55,name:'Áp chảo đúng độ chín'}},
 {icon:'RS',level:'CẢM GIÁC',title:'Rửa sạch theo quỹ đạo',goal:'Chà đều mặt rau bằng những vòng ngắn',standard:'Mục tiêu: 100% sạch',s:{...step('wash','rau theo mùa'),target:6,par:18,limit:50,name:'Rửa rau thật sạch'}},
 {icon:'NN',level:'NHỊP ĐIỆU',title:'Nêm đúng khoảnh khắc',goal:'Chạm hũ gia vị đúng bốn nhịp xanh',standard:'Mục tiêu: 4 lần vừa vị',s:{...step('season','nước sốt'),target:4,par:16,limit:45,name:'Nêm theo nhịp'}},
 {icon:'BD',level:'THẨM MỸ',title:'Bày đĩa cân đối',goal:'Đặt ba thành phần vào bố cục đầu bếp',standard:'Mục tiêu: 3/3 vị trí',s:{...step('plate','món hoàn thiện'),target:3,par:20,limit:55,name:'Bày đĩa nhà hàng'}},
 {icon:'BS',level:'PHỐI HỢP',title:'Bào sợi đổi chiều',goal:'Vuốt hết mặt bào và đổi hướng sau mỗi lượt',standard:'Mục tiêu: 8 lượt liền mạch',s:{...step('grate','cà rốt'),target:8,par:20,limit:55,name:'Bào cà rốt thành sợi'}},
 {icon:'NB',level:'LỰC TAY',title:'Nhào và gập bột',goal:'Đẩy khối bột luân phiên sang hai bên',standard:'Mục tiêu: 6 lần đúng hướng',s:{...step('knead','bột bánh'),target:6,par:24,limit:60,name:'Nhào bột đàn hồi'}},
 {icon:'TD',level:'SÁNG TẠO',title:'Tự do xếp topping',goal:'Chọn vị trí cho sáu topping trên món',standard:'Mục tiêu: đủ thành phần, không ra ngoài',s:{...step('assemble','topping'),target:6,par:28,limit:70,name:'Lắp ráp món tự do'}}
 ];const grid=node('div','','grid practice-grid goal-grid');for(const [index,g] of goals.entries()){const card=node('article','','card practice-card goal-card');card.append(node('span',g.icon,'skill-icon'),node('span',`BÀI ${index+1} · ${g.level}`,'eyebrow'),node('h3',g.title),node('p',g.goal),node('strong',g.standard,'goal-standard'),button('Bắt đầu bài tập',()=>start({id:'practice',name:g.title,country:'Phòng thực hành',emoji:g.icon,description:g.goal,steps:[g.s]},true)));grid.append(card)}page.append(grid)}
function installGuide(){const ua=navigator.userAgent,isApple=/iPhone|iPad|iPod/.test(ua),isAndroid=/Android/.test(ua);const d=node('dialog');d.className='install-guide';d.append(node('div','CÀI GAME TRÊN THIẾT BỊ','eyebrow'),node('h2',isApple?'iPhone / iPad':isAndroid?'Điện thoại Android':'Máy tính'));const list=node('ol');const steps=isApple?['Mở game bằng Safari.','Chạm nút Chia sẻ ở thanh công cụ.','Chọn “Thêm vào Màn hình chính”.','Mở biểu tượng World Kitchen và tải game một lần để chơi offline.']:isAndroid?['Mở game bằng Chrome.','Chạm menu ⋮.','Chọn “Cài đặt ứng dụng” hoặc “Thêm vào màn hình chính”.','Mở game từ biểu tượng mới; dữ liệu sẽ lưu riêng trên thiết bị.']:['Mở game bằng Chrome hoặc Edge.','Chọn biểu tượng cài đặt ở cuối thanh địa chỉ.','Bấm “Cài đặt” để mở game bằng cửa sổ riêng.','Mở game một lần khi có mạng để tải đủ dữ liệu offline.'];steps.forEach(s=>list.append(node('li',s)));d.append(list,node('p','Khi có bản mới, game sẽ báo “Cập nhật ngay”. Điểm và tiến trình không bị ghi đè.','install-note'));const actions=node('div','','actions');actions.append(button('Đã hiểu',()=>d.close()));d.append(actions);d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal()}
async function installGame(){if(installPrompt){await installPrompt.prompt();const choice=await installPrompt.userChoice;installPrompt=null;settings();status(choice.outcome==='accepted'?'Đã thêm World Kitchen vào máy.':'Bạn đã đóng yêu cầu cài đặt. Có thể dùng hướng dẫn cài thủ công bên dưới.');return}installGuide()}
function showUpdate(){const toast=get('update-toast');toast.hidden=false}
async function checkForUpdates(manual=false){if(!swRegistration){if(manual)status('Tự động cập nhật hoạt động ở bản production HTTPS sau khi cài game.');return}try{await swRegistration.update();if(swRegistration.waiting)showUpdate();else if(manual)status(`World Kitchen v${APP_VERSION} đang là bản mới nhất.`)}catch{if(manual)status('Chưa kiểm tra được bản mới. Hãy thử lại khi có mạng.')}}
function settings(){showPage('settings');const top=node('div','','page-title');top.append(node('div','GÓC ĐẦU BẾP','eyebrow'),node('h2','Cài đặt và bản lưu'),node('p','Điều chỉnh căn bếp cho vừa tay bạn. Mọi thay đổi được lưu ngay trên thiết bị.'));page.append(top);const panel=node('section','','settings-panel');
 const select=node('select');for(const [value,text]of[['easy','Dễ · vùng kéo rộng, thời gian dài'],['normal','Tiêu chuẩn']]){const o=node('option',text);o.value=value;select.append(o)}select.value=store.data.settings.difficulty;select.onchange=()=>store.settings({difficulty:select.value as Difficulty});const f=node('div','','field');f.append(node('label','Độ khó (lượt mới)'),select);panel.append(f);
 for(const [key,label] of [['muted','Tắt âm thanh'],['hints','Hiển thị gợi ý'],['reducedMotion','Giảm chuyển động']] as const){const field=node('div','','field'),input=node('input');input.type='checkbox';input.checked=store.data.settings[key];input.id=key;input.onchange=()=>{store.settings({[key]:input.checked});audio.settings=store.data.settings};const l=node('label',label);l.htmlFor=key;field.append(l,input);panel.append(field)}
 const volume=node('input');volume.type='range';volume.min='0';volume.max='1';volume.step='.05';volume.value=String(store.data.settings.volume);volume.id='volume';volume.oninput=()=>{store.settings({volume:Number(volume.value)});audio.settings=store.data.settings};const row=node('div','','field'),label=node('label','Âm lượng');label.htmlFor='volume';row.append(label,volume,button('Thử âm',async()=>{await audio.unlock();audio.play('success')},true));panel.append(row);page.append(panel);
 const installCard=node('section','','install-card');const installCopy=node('div');installCopy.append(node('span','CHƠI NHƯ GAME TẢI VỀ','eyebrow'),node('h3','Cài World Kitchen trên điện thoại, iPad hoặc máy tính'),node('p','Cài như một ứng dụng, mở toàn màn hình và chơi offline sau lần tải đầu. Hỗ trợ cả màn hình dọc lẫn ngang.'));const installActions=node('div','','install-actions');installActions.append(button(installPrompt?'Cài game ngay':'Xem cách cài',installGame),button('Kiểm tra bản mới',()=>void checkForUpdates(true),true));installCard.append(installCopy,installActions);page.append(installCard);
 const actions=node('div','','actions');actions.append(button('Xuất bản lưu',()=>{const url=URL.createObjectURL(new Blob([store.export()],{type:'application/json'})),a=node('a');a.href=url;a.download='World_Kitchen_Save_v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},true),button('Nhập bản lưu',()=>{const file=node('input');file.type='file';file.accept='.json,application/json';file.onchange=async()=>{const f=file.files?.[0];if(!f)return;try{if(f.size>100000)throw Error('Tệp quá lớn.');const raw=await f.text();confirmDialog('Nhập sẽ thay thế tiến độ và cài đặt hiện tại. Tiếp tục?',()=>{try{store.import(raw);audio.settings=store.data.settings;settings();status('Đã nhập bản lưu.')}catch(e){status(String(e))}})}catch(e){status(String(e))}};file.click()},true),button('Xóa dữ liệu chơi',()=>confirmDialog('Xóa toàn bộ điểm, cài đặt và lượt đang lưu trên trình duyệt này? Hãy xuất bản lưu trước nếu muốn giữ lại.',()=>{store.reset();audio.settings=store.data.settings;settings()}),true));page.append(actions,node('p',`Phiên bản ${APP_VERSION} · Tiến trình chỉ lưu cục bộ trên trình duyệt, không có tài khoản và không đồng bộ. Xóa dữ liệu trang web sẽ mất tiến trình; hãy xuất tệp JSON nếu muốn giữ hoặc chuyển máy.`),node('p','Lưu ý: việc gỡ PWA có xóa dữ liệu hay không tùy hệ điều hành. Nút “Xóa dữ liệu chơi” ở đây luôn xóa bản lưu của game.'));status()}
function recipeForMode(r:Recipe,mode:RunMode){if(mode!=='rush')return structuredClone(r);return{...structuredClone(r),steps:r.steps.map(s=>({...s,limit:Math.max(18,Math.round(s.limit*.72)),par:Math.max(10,Math.round(s.par*.8))}))}}
async function start(r:Recipe,isPractice=false,mode:RunMode='lesson'){if(!isPractice&&mode!=='rush'&&!unlock(r))return;if(!isPractice&&store.data.active){confirmDialog('Bắt đầu món mới sẽ thay lượt đang lưu. Tiếp tục?',()=>begin(r,isPractice,mode));return}begin(r,isPractice,mode)}
async function begin(r:Recipe,isPractice=false,mode:RunMode='lesson'){await audio.unlock();audio.settings=store.data.settings;audio.play('click');recipe=recipeForMode(r,mode);practice=isPractice;runMode=mode;run={recipeId:r.id,index:0,results:[],difficulty:store.data.settings.difficulty,mode};if(!practice)store.checkpoint(run);launch()}
function resume(){const active=store.data.active;if(!active)return;const base=active.recipeId==='service-dumplings'?serviceDumplingRecipe:recipes.find(r=>r.id===active.recipeId)!;runMode=active.mode??'lesson';if(runMode==='rush')activeOrder=serviceOrders.find(order=>order.dish.id===active.recipeId)??null;recipe=recipeForMode(base,runMode);run=structuredClone(active);practice=false;void audio.unlock();launch()}
function launch(){page.style.display='none';play.style.display='block';get('nav').replaceChildren();const strip=get('order-strip');if(runMode==='rush'&&activeOrder){strip.hidden=false;strip.replaceChildren(node('span',activeOrder.avatar,'order-avatar'),node('strong',`${activeOrder.name} · ${activeOrder.dish.name}`),node('span',activeOrder.tags.join(' · '),'order-request'),node('b',`♥ ${activeOrder.patience}s`))}else{strip.hidden=true;strip.replaceChildren()}if(!game){scene.onReady=loadStep;game=new Phaser.Game({type:Phaser.CANVAS,parent:'game',width:960,height:560,backgroundColor:'#bb9975',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[scene],audio:{noAudio:true},input:{activePointers:1}})}else{game.scale.refresh();loadStep()}}
function dialog(title:string,text:string,actions:HTMLButtonElement[]){get('overlay').style.display='flex';const d=get('dialog');d.className='dialog';d.replaceChildren(node('h2',title),node('p',text));const a=node('div','','actions');a.append(...actions);d.append(a)}
function reviewDialog(completed:boolean,title:string,result:StepResult,actions:HTMLButtonElement[]){get('overlay').style.display='flex';const d=get('dialog');d.className='dialog review-dialog';d.replaceChildren();const proof=node('div','','step-proof');try{const shot=node('img');shot.src=game?.canvas.toDataURL('image/jpeg',.82)??'';shot.alt=`Thành quả bước ${title}`;proof.append(shot)}catch{proof.append(node('div',recipe?.emoji??'✓','proof-fallback'))}proof.append(node('span',completed?'✓':'!','proof-badge'));const copy=node('div','','review-copy');copy.append(node('small',completed?'THÀNH QUẢ CÔNG ĐOẠN':'BÀI TẬP CHƯA ĐẠT','eyebrow'),node('h2',completed?`${title} hoàn tất`:'Hết thời gian'));const metrics=node('div','','review-metrics');for(const [value,label] of [[`${result.accuracy.toFixed(0)}%`,'CHÍNH XÁC'],[`${result.speed.toFixed(0)}%`,'TỐC ĐỘ'],[result.score.toFixed(1),'ĐIỂM']]){const item=node('div');item.append(node('strong',value),node('span',label));metrics.append(item)}copy.append(metrics);const a=node('div','','actions');a.append(...actions);copy.append(a);d.append(proof,copy)}
function loadStep(){
 if(!run||!recipe)return;phase='tutorial';stepResult=null;
 const current=recipe.steps[run.index];scene.hints=store.data.settings.hints;scene.motion=!store.data.settings.reducedMotion;scene.loadStepEngine(current,run.difficulty);
 const modeLabel=runMode==='rush'?'RUSH ORDER':runMode==='creative'?'BẾP SÁNG TẠO':practice?'LUYỆN TẬP':recipe.name.toUpperCase();
 get('step-label').textContent=`${modeLabel} · CÔNG ĐOẠN ${run.index+1}/${recipe.steps.length}`;get('step-title').textContent=current.name;get('instruction').textContent=current.hint;get('stage-label').textContent=stationLabel(current.kind);get('live-quality').textContent=`0 / ${current.target}`;
 const dots=get('step-dots');dots.replaceChildren(...recipe.steps.map((s,i)=>{const dot=node('span',String(i+1));dot.className=i<run!.index?'done':i===run!.index?'current':'';dot.title=s.name;return dot}));
 get('pause-slot').replaceChildren(button('Tạm dừng',pause,true));get('heat-controls').replaceChildren();get('feedback').textContent='Quan sát vật thể và làm theo đường dẫn';get('feedback').className='';
 const wrap=get('game-wrap');wrap.classList.remove('success-flash','error-flash','stage-enter');wrap.dataset.kind=current.kind;void wrap.offsetWidth;wrap.classList.add('stage-enter');
 if(current.kind==='boil'){const range=node('input');range.type='range';range.min='0';range.max='100';range.value='30';range.setAttribute('aria-label','Điều chỉnh nhiệt');range.oninput=()=>scene.engine.setHeat=Number(range.value);const change=(n:number)=>{if(phase!=='running')return;range.value=String(Math.max(0,Math.min(100,Number(range.value)+n)));scene.engine.setHeat=Number(range.value)};get('heat-controls').append(button('−',()=>change(-5)),range,button('+',()=>change(5)))}
 const units:Partial<Record<Recipe['steps'][number]['kind'],string>>={choose:'lựa chọn đúng theo order',boil:'giây trong vùng nhiệt chuẩn',wash:'mức làm sạch',plate:'thành phần đúng vị trí',grate:'lượt bào đổi chiều',knead:'lần đẩy và gập',assemble:'topping tự bố trí'},unit=units[current.kind]??'nhịp thao tác chính xác';
 const beginAction=()=>{phase='running';scene.paused=false;get('overlay').style.display='none';void audio.unlock()};
 if(run.index>0&&(runMode==='rush'||runMode==='creative')){
  get('overlay').style.display='flex';const d=get('dialog');d.className='dialog station-splash';d.replaceChildren(node('span',stationLabel(current.kind),'eyebrow'),node('h2',current.name),node('p',current.hint),node('strong',`${current.target} ${unit}`,'splash-goal'));const expectedIndex=run.index;window.setTimeout(()=>{if(phase==='tutorial'&&run?.index===expectedIndex)beginAction()},850);
 }else dialog(current.name,`${current.hint}\nMục tiêu: ${current.target} ${unit}.`,[button(runMode==='rush'?'Bắt đầu order':'Bắt đầu',beginAction),button('Về menu',leave,true)]);
}
function leave(){scene.paused=true;scene.cancel();menu()}
function pause(){if(phase!=='running')return;phase='paused';scene.paused=true;scene.cancel();dialog('Bếp đang nghỉ','Thời gian và thao tác đã dừng.',[button('Tiếp tục',()=>{phase='running';scene.paused=false;get('overlay').style.display='none'}),button('Làm lại bước',loadStep,true),button('Về menu',leave,true)])}
let feedbackTimer=0;
scene.onFeedback=ok=>{audio.play(ok?'cut':'error');const wrap=get('game-wrap'),feedback=get('feedback');wrap.classList.remove('success-flash','error-flash');void wrap.offsetWidth;wrap.classList.add(ok?'success-flash':'error-flash');feedback.className=ok?'good':'bad';if('vibrate'in navigator)navigator.vibrate(ok?18:[25,30,25]);window.clearTimeout(feedbackTimer);feedbackTimer=window.setTimeout(()=>{wrap.classList.remove('success-flash','error-flash');feedback.className=''},650)};
scene.notify=()=>{
 if(!scene.engine||phase==='menu')return;
 const e=scene.engine,remaining=Math.max(0,Math.ceil(e.step.limit-e.elapsed)),timer=get('timer');timer.textContent=`${remaining} giây`;timer.parentElement?.classList.toggle('urgent',remaining<=10);get('feedback').textContent=e.hint;
 const live=e.step.kind==='boil'?`${e.amount.toFixed(1)} / ${e.step.target}s`:e.step.kind==='mix'?`${e.amount.toFixed(1)} / ${e.step.target}`:`${e.accepted} / ${e.step.target}`;get('live-quality').textContent=live;const progress=get('progress') as HTMLProgressElement;progress.value=e.progress;progress.style.setProperty('--value',`${e.progress*100}%`);
 if(e.done&&phase==='running'){
  phase='review';scene.paused=true;stepResult=scoreStep(e.accuracy,e.elapsed,e.step.par,e.step.limit,e.completed);audio.play(e.completed?'success':'error');
  const last=run!.index===recipe!.steps.length-1,fluid=e.completed&&!last&&(runMode==='rush'||runMode==='creative');
  if(fluid){get('overlay').style.display='flex';const d=get('dialog');d.className='dialog flow-pass';d.replaceChildren(node('span','✓','flow-check'),node('strong',e.step.name+' hoàn tất'),node('small',runMode==='rush'?'Chuyển trạm ngay · khách vẫn đang chờ':'Tiếp tục sáng tạo · không ngắt nhịp'));const expectedIndex=run!.index;window.setTimeout(()=>{if(phase==='review'&&run?.index===expectedIndex)next()},650)}
  else reviewDialog(e.completed,e.step.name,stepResult,[button(last?'Xem thành phẩm':'Bước tiếp theo',next),button('Thử lại',loadStep,true),button('Về menu',leave,true)]);
 }
};
function next(){if(!run||!recipe||!stepResult||phase!=='review')return;run.results.push(stepResult);run.index++;if(run.index<recipe.steps.length){if(!practice)store.checkpoint(run);loadStep()}else{if(!practice)store.finish(recipe.id,run.results);resultsPage()}}
function resultsPage(){const r=recipe!,scores=run!.results,score=average(scores);showPage();audio.play('finish');const resultHero=node('section','','result-hero');for(let i=0;i<18;i++){const bit=node('i','','confetti');bit.style.setProperty('--x',`${(i*47)%100}%`);bit.style.setProperty('--delay',`${(i%6)*.12}s`);bit.style.setProperty('--color',['#efb94c','#e66951','#73a878','#f7eee0'][i%4]);resultHero.append(bit)}const dish=r.art?node('img'):node('div',r.emoji);dish.className=r.art?'result-photo':'result-dish';if(r.art&&dish instanceof HTMLImageElement){dish.src=r.art;dish.alt=`Thành phẩm ${r.name}`}const resultKicker=runMode==='rush'?'ORDER ĐÃ GIAO ĐÚNG HẸN':runMode==='creative'?'MÓN ĐỘC BẢN ĐÃ HOÀN THIỆN':score>=85?'TUYỆT HẢO, BẾP TRƯỞNG!':score>=70?'MÓN NGON ĐÃ SẴN SÀNG':'HOÀN THÀNH MÓN ĂN';resultHero.append(dish,node('div',resultKicker,'eyebrow'),node('h2',r.name+' hoàn thành','center'),node('div','★'.repeat(stars(score))+'☆'.repeat(5-stars(score)),'center result-stars'),node('strong',`${score.toFixed(1)} / 100`,'result-score'),node('p',practice?'Ca tự do hoàn thành · Kết quả không ảnh hưởng hành trình':store.message,'center'));if(runMode==='rush'&&activeOrder){const reward=Math.round(activeOrder.reward*(.65+score/285)),tip=Math.max(0,Math.round((score-65)/8));const payout=node('div','','payout');payout.append(node('span',`Tiền món +${reward}k`),node('span',`Tip +${tip}k`),node('strong',score>=85?'Khách rất hài lòng':'Đã phục vụ xong'));resultHero.append(payout)}page.append(resultHero);const table=node('table','','score-table'),head=node('tr');for(const t of ['Thao tác','Chính xác','Tốc độ','Điểm'])head.append(node('th',t));table.append(head);scores.forEach((s,i)=>{const row=node('tr');row.append(node('td',r.steps[i].name),node('td',s.accuracy.toFixed(0)+'%'),node('td',s.speed.toFixed(0)+'%'),node('td',s.score.toFixed(1)));table.append(row)});page.append(table);const a=node('div','','actions result-actions'),base=r.id==='service-dumplings'?serviceDumplingRecipe:(recipes.find(item=>item.id===r.id)??r);if(runMode==='rush')a.append(button('Phục vụ khách tiếp theo',()=>{activeOrder=null;serviceShift()}),button('Làm lại order',()=>start(base,practice,runMode),true));else a.append(button(runMode==='creative'?'Mở hộp khác':practice?'Làm lại bài':'Nấu lại',()=>start(base,practice,runMode)));a.append(button('Về sảnh bếp',menu,true));page.append(a);if(!practice){const unlocked=recipes.find(candidate=>candidate.requires===r.id);if(unlocked&&unlock(unlocked))page.append(node('p',`🎉 Đã mở món ${unlocked.name}!`,'center unlock-celebration'))}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();else void checkForUpdates(false)});window.addEventListener('blur',pause);
window.addEventListener('keydown',e=>{if(e.key==='Escape')pause()});
get('apply-update').addEventListener('click',()=>{swRegistration?.waiting?.postMessage({type:'SKIP_WAITING'})});
get('dismiss-update').addEventListener('click',()=>{get('update-toast').hidden=true});
if(import.meta.env.PROD&&'serviceWorker'in navigator){let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()});window.addEventListener('load',async()=>{try{swRegistration=await navigator.serviceWorker.register(import.meta.env.BASE_URL+'sw.js');if(swRegistration.waiting)showUpdate();swRegistration.addEventListener('updatefound',()=>{const worker=swRegistration?.installing;if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)showUpdate()})});window.setInterval(()=>void checkForUpdates(false),60*60*1000)}catch{/* Offline cache remains optional when the host blocks service workers. */}})}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event as InstallPromptEvent});
window.addEventListener('appinstalled',()=>{installPrompt=null});
menu();
